# PyTorch Basics Exercises
For these exercises we'll create a tensor and perform several operations on it.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

### 1. Perform standard imports
Import torch and NumPy

In [1]:
# CODE HERE
import numpy as np
import torch

### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [4]:
# CODE HERE
np.random.seed(42)
torch.manual_seed(42) 


### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [13]:
# CODE HERE
np.random.seed(42)
arr=np.random.randint(0,4,6)
arr

array([2, 3, 0, 2, 2, 3])

### 4. Create a tensor "x" from the array above

In [17]:
# CODE HERE
x = torch.as_tensor(arr)
x

tensor([2, 3, 0, 2, 2, 3])

### 5. Change the dtype of x from 'int32' to 'int64'
Note: 'int64' is also called 'LongTensor'

In [19]:
# CODE HERE
x=x.type(torch.int64)


In [20]:
x

tensor([2, 3, 0, 2, 2, 3])

In [21]:
type(x)

torch.Tensor

### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [22]:
# CODE HERE
x=x.view(3,2)
x

tensor([[2, 3],
        [0, 2],
        [2, 3]])

### 7. Return the right-hand column of tensor x

In [24]:
# CODE HERE
x[:,1:]


tensor([[3],
        [2],
        [3]])

### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [25]:
# CODE HERE
x_seq=x**2
x_seq

tensor([[4, 9],
        [0, 4],
        [4, 9]])

### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [28]:
# CODE HERE
#x.shape
#torch.Size([3, 2]) # so the y should be 2X something
y=torch.randint(low=0,high=4,size=(2,3))
y

tensor([[2, 3, 0],
        [2, 2, 3]])

### 10. Find the matrix product of x and y

In [29]:
# CODE HERE
torch.mm(x,y) 


tensor([[10, 12,  9],
        [ 4,  4,  6],
        [10, 12,  9]])

## Great job!